version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: process.env.DATABASE_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - process.env.DATABASE_DOCKERVOLUME 